Repository devkjoon/krn, pull requests merged in 2023-01, with the labels that each got.

#14 modified index.html
  images/KRN Logo PNG.png
  images/deadlift.png
  images/run.png
  index.html
Labels: enhancement

#15 Alexandria
  .env.EXAMPLE
  config/connection.js
  controllers/api/home-routes.js
  controllers/api/index.js
  controllers/api/user-routes.js
  controllers/index.js
  models/User.js
  package-lock.json
  package.json
  public/css/login.js
  public/css/logout.js
  server.js
  views/layouts/main.handlebars
  views/login.handlebars
Labels: enhancement

#16 Added login page and styling
  css/style.css
  images/pexels-victor-freitas-841130.jpg
  images/run.jpg
  js/slider-index.js
  login.html
Labels: enhancement

#25 Login is listening, still need to change add logic
  config/connection.js
  controllers/api/home-routes.js
  controllers/home-routes.js
  db/schema.sql
  models/Gallery.js
  models/Painting.js
  models/index.js
  seeds/galleryData.js
  seeds/index.js
  seeds/paintingData.js
  server.js
  utils/helpers.js
  views/gallery.handlebars
  views/homepage.handlebars
  views/painting.handlebars
  views/partials/gallery-details.handlebars
  views/partials/painting-details.handlebars
Labels: enhancement

#26 Login no longer throwing error. Working on cleaning code up
  package.json
  public/css/jass.css
  public/css/style.css
  public/images/01-blossoming-apricot.jpg
  public/images/02-cosmos-flowers.jpg
  public/images/03-sand-sea-summer.jpg
  public/images/04-beach-chairs.jpg
  public/images/05-beach-sunrise.jpg
  public/images/06-fall-colors.jpg
  public/images/07-autumn-mountains.jpg
  public/images/08-frozen-river.jpg
  public/images/09-winter-home.jpg
  public/js/login.js
  public/js/logout.js
Labels: enhancement

#27 Adding workouts to seeds
  public/images/burpee.PNG
  public/images/lunges.jpg
  public/images/overheadpress.PNG
  public/images/swissballcurl.PNG
  seeds/galleryData.js
  seeds/paintingData.js
Labels: enhancement

#38 Login is now working and storing passwords
  public/js/login.js
Labels: bug

#40 modified homepage to display appropriate values
  public/css/style.css
  public/images/John Brown.png
  views/homepage.handlebars
Labels: enhancement

#42 Updating workouts view
  controllers/home-routes.js
  views/Workout.handlebars
  views/layouts/main.handlebars
Labels: bug

#41 update
  views/homepage.handlebars
Labels: enhancement

#43 Corrected exercises. Images now showing
  views/Exercises.handlebars
Labels: bug, enhancement

#45 Added APIs
  public/js/activities/activities.js
  public/js/calculators/bmi.js
  public/js/calculators/bodyfat.js
  public/js/calculators/claburn.js
  public/js/calculators/dailycalreq.js
  public/js/calculators/idealweight.js
  public/js/foods/foodinfo.js
  public/js/foods/foodnames.js
  public/js/foods/subtable.js
  public/js/foods/tablenames.js
Labels: enhancement

#46 updated calburn name
  public/js/calculators/calburn.js
Labels: enhancement

#48 added photos to carousel
  public/images/food.jpg
  public/images/scale.jpeg
  views/homepage.handlebars
Labels: enhancement

#56 Got exercises working
  controllers/home-routes.js
  models/Exercises.js
  package-lock.json
  package.json
  public/js/exerciseDB/exercisebyid.js
  public/js/exerciseDB/listbybodyparts.js
  public/js/exerciseDB/listbyequipment.js
  public/js/exerciseDB/listbyname.js
  public/js/exerciseDB/listbytargetmuscles.js
  public/js/exerciseDB/listofallexercises.js
  public/js/exerciseDB/listofbodyparts.js
  public/js/exerciseDB/listofexerciseofequipment.js
  seeds/exercisesData.js
  views/Exercises.handlebars
Labels: enhancement

#57 BMI is working! Need to add inputs
  controllers/contact.js
  controllers/home-routes.js
  models/bmi.js
  views/bmi.handlebars
Labels: enhancement

#58 exercises now show, working on backend for drop down
  controllers/home-routes.js
  seeds/exercisesData.js
  seeds/workoutData.js
  views/bodypartlist.handlebars
  views/partials/Exercises-details.handlebars
  views/partials/Workout-details.handlebars
  views/targetlist.handlebars
Labels: enhancement

#60 Added nav bar to bmi handlebars
  public/js/calculators/bmi.js
  views/bmi.handlebars
  views/bmiinput.handlebars
  views/homepage.handlebars
  views/welcome.handlebars
Labels: enhancement

#62 working on bmiinput handlebars
  controllers/api/bmi-routes.js
  controllers/api/index.js
  controllers/home-routes.js
  public/js/calculators/bmi.js
  views/bmiinput.handlebars
Labels: enhancement

#64 Moved bmi out of the api folder. bmiinputs is grabbing the user input. Still need to fix the fetch
  controllers/api/bmi-routes.js
  controllers/api/index.js
  controllers/home-routes.js
  controllers/index.js
  models/bmi.js
  models/index.js
  public/js/calculators/bmi.js
  seeds/index.js
  views/bmiinput.handlebars
Labels: enhancement

#66 Updated bmi path. Now working!
  controllers/home-routes.js
  public/js/calculators/bmi.js
Labels: bug

#67 Updated hardcoded handlebars for bmi route
  views/bmi.handlebars
  views/bmiinput.handlebars
  views/homepage.handlebars
  views/welcome.handlebars
Labels: enhancement

#69 fixed icons on bmi handlebars
  views/bmi.handlebars
  views/bmiinput.handlebars
Labels: bug

#74 Updated path for home-routes.js
  controllers/home-routes.js
  public/js/calculators/bmi.js
Labels: enhancement

#75 Updated Form and converted to lbs and inches for bmi
  controllers/home-routes.js
  views/bmi.handlebars
  views/bmiinput.handlebars
Labels: enhancement
